version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data

  appserver:
    build:
      context: ../../.
      dockerfile: PKWAT.ScoringPoker.Server/Dockerfile
    depends_on:
        - db

  web:
    build:
      context: ../../.
      dockerfile: PKWAT.ScoringPoker.UI.Web/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
        - appserver